Data types and number
Phantomcheg/js-basic pull request #2
Opened 2019-10-10 08:37 UTC by Phantomcheg

2019-10-10 15:02 UTC, lizarusi requested changes
everything is perfect, small notes added

2019-10-10 15:02 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +dataTypes.forEach((item) => {
👍

2019-10-10 15:02 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +  finalObject[typeof arrayItem] = (finalObject[typeof arrayItem] || null) + 1;
dangerous type conversion here! you are doing `|| null` and lucky for you it casts to `0` but you may got `NaN` for example. just do obviously `|| 0`

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +function workWithArrays(anyArray) {
add more meaningful names for functions `getAverage` for example. `anyArray` also not quite good, just `array` will be enough.

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  let summary = null;
same issue as above: just `let summary = 0`

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  return parseFloat(summary).toFixed(3);
it is sum, but not average

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +for (let i = 0; i <= 5; i++) {
make length random as well :)

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  arrayForCalc.push(Math.random()*10);
don't forgot to run `npm run lint` and fix problems. Spaces are missed

2019-10-10 15:02 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  arrayForCalc.push(Math.random()*10);
let's complicate a task, generate random hex numbers, and in function above parse them to decimal value

2019-10-10 15:29 UTC, Mike-Savin requested changes
See Liza's comments

2019-10-11 09:28 UTC, Phantomcheg commented
Done remarks you made

2019-10-11 10:01 UTC, lizarusi approved these changes
Small notes added, but in general perfect :)

2019-10-11 10:01 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +  array.forEach((arrayItem) => {
you can also do it with `reduce`, you can check if you want :) https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2019-10-11 10:01 UTC, lizarusi commented on Exercises/numbers/numbers.js
> +const arrayForCalc = [];
better not to cut variables name, so better name will be `arrayForCalculation`

2019-10-13 14:03 UTC, Mike-Savin approved these changes
Looks good 👍, just see our comments for the future

2019-10-13 14:03 UTC, Mike-Savin commented on Exercises/numbers/numbers.js
> +const roundedRandomDecimal = Math.round(randomNumber(1, 100));
By the way, Math.round here also can be omitted

2019-10-13 14:03 UTC, Mike-Savin commented on Exercises/numbers/numbers.js
> +  return (summary/array.length).toFixed(3);
It's better to use spaces around operators

2019-10-17 09:09 UTC, merged